baseURL = "/"
languageCode = "en-us"
title = "Raahul Singh"
theme = "gwern-inspired"
enableGitInfo = true
enableRobotsTXT = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  description = "Personal website and digital garden"
  author = "Raahul Singh"
  mainSections = ["essays", "notes", "reading"]
  images = ["images/profile.jpg"]
  enableToc = true
  enableSidenotes = false
  enableTooltips = true
  enableGitInfo = true
  dateFormat = "Jan 2, 2006"
  
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Essays"
url = "/essays/"
weight = 2

[[menu.main]]
name = "Notes"
url = "/notes/"
weight = 3

[[menu.main]]
name = "Reading List"
url = "/reading/"
weight = 4

[[menu.main]]
name = "About"
url = "/about/"
weight = 5 