name: The Melange
title: The Melange - What We Keep from Life's Many Wonders
description: description: The word "Melange" refers to an assortment of disparate and often incongruous elements, much like the journey through life itself. There is so much to explore, to learn, to discover, to understand, and hopefully when my time comes, to leave behind. This particular melange belongs to me, and I wish to fill it with everything I fall in love with, from math, science, tech to introspective philosophy and poetry, with no defined goal or destination in mind. Tolkien once said, "Not all who wander are lost." Perhaps, one must wander to not be lost.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: raahulsingh002@gmail.com
# # See: https://disqus.com/
# disqus_username: disqus_username
# # Contact Form Setting
# # See: https://formspree.io/
# formspree_form_id: formspree_form_id
